language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install coveralls
before_script:
  - export PYTHONPATH='./'
script:
  - coverage run --source=src -m pytest unittests/
after_success:
  - coveralls